#!/usr/bin/env bash
# ==============================================================================
# install.sh — Chromebook Crostini Zsh power-user bootstrap
# Idempotent: safe to run more than once.
# ==============================================================================
set -euo pipefail

PLUGIN_DIR="$HOME/.zsh/plugins"
DOTFILE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Colour helpers ─────────────────────────────────────────────────────────────
green()  { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$*"; }
red()    { printf '\033[0;31m%s\033[0m\n' "$*"; }
info()   { printf '\033[0;36m[*]\033[0m %s\n'  "$*"; }
ok()     { printf '\033[0;32m[✔]\033[0m %s\n'  "$*"; }
warn()   { printf '\033[0;33m[!]\033[0m %s\n'  "$*"; }
die()    { printf '\033[0;31m[✘]\033[0m %s\n'  "$*" >&2; exit 1; }

# ── Dependency check ───────────────────────────────────────────────────────────
need_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Required: $1 is not installed."
}

need_cmd git
need_cmd curl
need_cmd apt-get

# ── APT packages ───────────────────────────────────────────────────────────────
APT_PACKAGES=(
  zsh
  git
  neovim
  ripgrep
  fd-find
  fzf
  direnv
  unzip
  p7zip-full
  zsh-syntax-highlighting
  zsh-autosuggestions
)

info "Updating apt and installing packages…"
sudo apt-get update -qq
sudo apt-get install -y "${APT_PACKAGES[@]}"
ok "APT packages installed."

# fd-find ships as fdfind on Debian; symlink to fd if missing
if command -v fdfind >/dev/null 2>&1 && ! command -v fd >/dev/null 2>&1; then
  sudo ln -sf "$(command -v fdfind)" /usr/local/bin/fd
  ok "Linked fdfind → /usr/local/bin/fd"
fi

# ── Optional: zoxide ───────────────────────────────────────────────────────────
if ! command -v zoxide >/dev/null 2>&1; then
  info "Installing zoxide…"
  curl -fsSL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
  ok "zoxide installed."
else
  ok "zoxide already present."
fi

# ── Optional: starship ─────────────────────────────────────────────────────────
if ! command -v starship >/dev/null 2>&1; then
  info "Installing starship…"
  curl -fsSL https://starship.rs/install.sh | sh -s -- --yes
  ok "starship installed."
else
  ok "starship already present."
fi

# ── fzf shell integration ──────────────────────────────────────────────────────
if [[ ! -f ~/.fzf.zsh ]]; then
  if [[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ]]; then
    info "Installing fzf shell integration…"
    # fzf from apt doesn't run the install script; source from the examples dir
    mkdir -p ~/.fzf
    cp /usr/share/doc/fzf/examples/key-bindings.zsh ~/.fzf/key-bindings.zsh
    cp /usr/share/doc/fzf/examples/completion.zsh ~/.fzf/completion.zsh 2>/dev/null || true
    cat > ~/.fzf.zsh <<'EOF'
# fzf shell integration (generated by install.sh)
[[ -f ~/.fzf/key-bindings.zsh ]] && source ~/.fzf/key-bindings.zsh
[[ -f ~/.fzf/completion.zsh   ]] && source ~/.fzf/completion.zsh
EOF
    ok "fzf shell integration written to ~/.fzf.zsh"
  else
    warn "fzf examples not found; skipping shell integration."
  fi
else
  ok "~/.fzf.zsh already present."
fi

# ── Git plugins (cloned, depth=1 for speed) ────────────────────────────────────
declare -A PLUGINS=(
  [zsh-completions]="https://github.com/zsh-users/zsh-completions"
  [zsh-autosuggestions]="https://github.com/zsh-users/zsh-autosuggestions"
  [zsh-history-substring-search]="https://github.com/zsh-users/zsh-history-substring-search"
  [fast-syntax-highlighting]="https://github.com/zdharma-continuum/fast-syntax-highlighting"
  [zsh-vi-mode]="https://github.com/jeffreytse/zsh-vi-mode"
)

mkdir -p "$PLUGIN_DIR"

for name in "${!PLUGINS[@]}"; do
  target="$PLUGIN_DIR/$name"
  if [[ -d $target ]]; then
    info "Updating plugin: $name"
    git -C "$target" pull --ff-only --quiet
    ok "$name updated."
  else
    info "Cloning plugin: $name"
    git clone --depth=1 "${PLUGINS[$name]}" "$target" --quiet
    ok "$name cloned."
  fi
done

# ── Starship config (minimal, sensible defaults) ───────────────────────────────
STARSHIP_CFG="$HOME/.config/starship.toml"
if [[ ! -f $STARSHIP_CFG ]]; then
  mkdir -p "$(dirname "$STARSHIP_CFG")"
  cp "$DOTFILE_DIR/themes/starship.toml" "$STARSHIP_CFG" 2>/dev/null || \
  cat > "$STARSHIP_CFG" <<'EOF'
# starship.toml — generated by install.sh
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[character]
success_symbol = "[❯](green)"
error_symbol   = "[❯](red)"
vimcmd_symbol  = "[❮](yellow)"

[directory]
truncation_length = 4
truncate_to_repo  = true

[git_branch]
symbol = " "

[git_status]
ahead  = "⇡${count}"
behind = "⇣${count}"
staged = "[+${count}](green)"
modified = "[!${count}](yellow)"
untracked = "[?${count}](red)"

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[kotlin]
symbol = " "

[time]
disabled  = false
format    = "[$time]($style) "
style     = "dimmed white"
EOF
  ok "starship.toml written."
else
  ok "starship.toml already exists, skipping."
fi

# ── Deploy .zshrc ──────────────────────────────────────────────────────────────
ZSHRC_SRC="$DOTFILE_DIR/.zshrc"
ZSHRC_DST="$HOME/.zshrc"

if [[ -f $ZSHRC_DST && ! -L $ZSHRC_DST ]]; then
  backup="$ZSHRC_DST.bak.$(date +%Y%m%d_%H%M%S)"
  warn "Backing up existing ~/.zshrc → $backup"
  cp "$ZSHRC_DST" "$backup"
fi

ln -sf "$ZSHRC_SRC" "$ZSHRC_DST"
ok "~/.zshrc symlinked from repo."

# ── Set Zsh as default shell ───────────────────────────────────────────────────
ZSH_BIN=$(command -v zsh)
if [[ "$SHELL" != "$ZSH_BIN" ]]; then
  info "Setting default shell to $ZSH_BIN…"
  chsh -s "$ZSH_BIN"
  ok "Default shell changed. Log out and back in to apply."
else
  ok "Zsh is already the default shell."
fi

# ── Cache directory ────────────────────────────────────────────────────────────
mkdir -p "$HOME/.cache/zsh/compcache"
ok "Zsh cache directory ready."

# ── Done ───────────────────────────────────────────────────────────────────────
printf '\n'
green "══════════════════════════════════════════"
green "  Installation complete."
green "  Open a new terminal or run: zsh"
green "══════════════════════════════════════════"
